name: linter
on: push
jobs:
  start-linter:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: actions/checkout@v1
        
      - name: install composer inquires
        run: make install
      
      - name: run linter
        run: make lint
